#!/bin/sh
if ! cd `dirname $0`; then
	echo "Could not cd to source directory."
	exit 1
fi

PERSISTENT_PATH=`scripts/zfsci-get-config persistent_path`

rsync -av --delete scripts/ $PERSISTENT_PATH/scripts/
rsync -av --delete tasks/ $PERSISTENT_PATH/tasks/
cp zfsci.conf $PERSISTENT_PATH/
