#!/usr/bin/env python
import sys
import os
import glob
import json

sourcedir = os.path.dirname(os.path.realpath(__file__))
os.chdir(sourcedir)

sys.path.append('scripts/')
from tasklib import Attribute

for taskfile in glob.glob('jobs/*.py'):
	execfile(taskfile)

try:
	os.makedirs('build/jobs')
except OSError:
	pass

jobdescs = Attribute.get_jobdescs()
for jobdesc in jobdescs:
	fp = open('build/jobs/%s.json' % (jobdesc['job_id']), 'w')
	json.dump(jobdesc, fp)
	fp.close()

print 'Successfully built %d job descriptions.' % (len(jobdescs))

sys.exit(0)
