#!/bin/sh
aptitude install -y module-assistant zlib1g-dev uuid-dev
module-assistant prepare -i

mkdir -p /root/build

cd /root/build
git clone git://github.com/behlendorf/zfs.git

cd zfs
./configure --prefix=/usr
make -j 4
if make install; then
	zfsci-finish-task PASSED
else
	zfsci-finish-task FAILED
fi
