#!/bin/sh
if ! cd `dirname $0`; then
	echo "Could not cd to scripts directory."
	exit 1
fi

if [ -z "$1" ]; then
	echo "Syntax: $0 <port>"
	exit 1
fi

CONTROLHOST=`./zfsci-get-config power_hostname`
CONTROLPORT=`./zfsci-get-config power_port`
CONTROLUSER=`./zfsci-get-config power_username`
CONTROLPASS=`./zfsci-get-config power_password`

PORT=$1

telnet $CONTROLHOST $CONTROLPORT >/dev/null 2>&1 <<COMMANDS
login $CONTROLUSER $CONTROLPASS
port $PORT int
quit
COMMANDS

exit 0
