#!/bin/sh
if ! cd `dirname $0`; then
	echo "Could not cd to scripts directory."
	exit 1
fi

if [ -z "$2" ]; then
	echo "Syntax: $0 <port> <\"0\"|\"1\"|\"int\">"
	exit 1
fi

CONTROLHOST=`./zfsci-get-config power_hostname`
CONTROLPORT=`./zfsci-get-config power_port`
CONTROLUSER=`./zfsci-get-config power_username`
CONTROLPASS=`./zfsci-get-config power_password`

PORT=$1
MODE=$2

# reset the host using the IP power strip's "kshell" interface
telnet $CONTROLHOST $CONTROLPORT >/dev/null 2>&1 <<COMMANDS
login $CONTROLUSER $CONTROLPASS
port $PORT $MODE
quit
COMMANDS

exit 0
