#!/bin/sh
if [ -z "$1" ]; then
	echo "Syntax: $0 <task>"
	exit 1
fi

TASK=$1

if [ ! -e $TASK ]; then
	echo "Task not found: $TASK"
	exit 1
fi

export RESULTDIR=/var/lib/zfsci/$TASK
mkdir -p $RESULTDIR

echo -n "Running $TASK... "
chmod u+x $TASK
SCRIPTDIR=`dirname $0`
PATH=`readlink -f $SCRIPTDIR`:$PATH $TASK \
	0</dev/null \
	1>$RESULTDIR/stdout \
	2>$RESULTDIR/stderr \
	3>$RESULTDIR/status

if [ -z "`cat $RESULTDIR/status`" ]; then
	echo "FAILED" > $RESULTDIR/status
fi

cat $RESULTDIR/status

exit 0
