#!/bin/sh
if ! cd `dirname $0`; then
	echo "Could not cd to scripts directory."
	exit 1
fi

if [ -z "$1" ]; then
	echo "Syntax: $0 <config>"
	echo "Configures a zfsci node using the specified config."
	exit 1
fi

CONFIG=$1

if ! ./zfsci-mount-node; then
	echo "Node root FS could not be mounted."
	exit 1
fi

if [ ! -f $CONFIG ]; then
	echo "The config file you specified does not exist."
	exit 1
fi

# mark the tests as 'in progress'
touch /mnt/.zfsci

# copy zfsci scripts
rm -f /mnt/opt/zfsci
ln -s /var/lib/zfsci-data/opt-zfsci /mnt/opt/zfsci

# copy test config
mkdir -p /mnt/var/lib/zfsci
cp $CONFIG /mnt/var/lib/zfsci/job.json

# mount persistent dir
if ! mountpoint -q /mnt/var/lib/zfsci-data; then
	mkdir -p /mnt/var/lib/zfsci-data
	mount --bind /var/lib/zfsci-data /mnt/var/lib/zfsci-data
fi

# run build tasks
chroot /mnt /opt/zfsci/zfsci-run-stage /var/lib/zfsci-data/tasks build /var/lib/zfsci/job.json

exit 0
