#!/usr/bin/env python
import sys
import os
import glob
from tasklib import JobConfig, Dispatcher

if len(sys.argv) < 3:
	print 'Syntax: %s <config-file> <parameter>' % (sys.argv[0])
	sys.exit(1)

configfile = sys.argv[1]
parameter = sys.argv[2]

if not os.path.isfile(configfile):
	print 'Config file "%s" does not exist.' % (configfile)
	sys.exit(1)

JobConfig.load(configfile)
print JobConfig.get_input(parameter, '')
sys.exit(0)
