#!/usr/bin/env python
import os
import sys
from partlib import PartitionBuilder

PartitionBuilder.mount_partitions()

if not os.system("kexec --command-line='root=%s ro crashkernel=128M' " % (PartitionBuilder.get_rootpart()) + \
		"--initrd=/mnt/initrd.img /mnt/vmlinuz"):
	sys.exit(1)

sys.exit(0)
