#!/bin/sh
if [ -z "$1" ]; then
	echo "Syntax: $0 <timeout>"
	echo "Causes a kernel panic in <timeout> seconds unless"
	echo "the timer is re-armed by resetting the timeout."

	exit 1
fi

TIMEOUT=$1

PIDFILE=/var/run/zfsci-watchdog.pid

if [ -f $PIDFILE ]; then
	kill -KILL `cat $PIDFILE`
fi

if [ $TIMEOUT -gt 0 ]; then
	(exec sh -c "echo \$\$ > $PIDFILE; sleep $TIMEOUT; echo c > /proc/sysrq-trigger" &)

	# TODO: find a more reliable way of checking that the sub-shell has written its pid file.
	sleep 1

	echo "Watchdog has been (re-)armed: $TIMEOUT seconds"
else
	echo "Watchdog has been disabled."
fi

exit 0
