#!/usr/bin/env python2.6
import sys
import os
import json
import cgi
import shutil
from datetime import datetime
from joblib import Job, JobResult, TaskResult, get_job_session
from tasklib import Utility
from hashlib import md5

if len(sys.argv) < 2:
	print "Syntax: %s <output-dir>" % (sys.argv[0])
	sys.exit(1)

resultdir = sys.argv[1]

session = get_job_session()
jobs = Job.find_all(session)

try:
	os.makedirs(resultdir + '/jobs')
except OSError:
	pass

try:
	os.makedirs(resultdir + '/results')
except OSError:
	pass

try:
	os.makedirs(resultdir + '/output')
except OSError:
	pass

shutil.copy(Utility.get_source_dir() + '/misc/zfsci.png', resultdir)

def taskresult_to_color(result):
	status = result.status

	if status in [TaskResult.DEPENDENCY_ERROR, TaskResult.PENDING, TaskResult.RUNNING]:
		return 'orange'
	elif status == TaskResult.FAILED:
		return 'red'
	else:
		return 'green'

# detailed job/result pages
for job in jobs:
	jfp = open(resultdir + '/jobs/' + job.hash + '.html', 'w')

	attribs = json.JSONEncoder(indent=1).encode(job.attributes)

	jfp.write("""
<html>
<head>
	<title>Job: %s</title>
</head>
<body>
<h1>Job %s</h1>

<h2>Input</h2>
<pre>%s</pre>

<h2>Results</h2>
<ul>
""" % (job.hash, job.hash, cgi.escape(attribs)))

	for result in job.results:
		jfp.write("""
<li><a href="../results/%s.html">%s</a></li>
""" % (result.hash, result.hash))

		rfp = open(resultdir + '/results/' + result.hash + '.html', 'w')

		rfp.write("""
<html>
<head>
	<title>Result: %s</title>
</head>
<body>
<h1>Result %s</h1>

<h2>Job</h2>
<a href="../jobs/%s.html">%s</a>

<h2>General Information</h2>
<table>
  <tr>
    <td>Time:</td>
    <td>%s - %s (%s)</td>
  </tr>
</table>

<h2>Tasks</h2>
""" % (result.hash, result.hash, job.hash, job.hash, \
	result.run_start, '?' if result.run_end == None else result.run_end, \
	'incomplete' if result.run_end == None else result.run_end - result.run_start))

		def cmp_end_time(x, y):
			if x.run_end == None:
				return 1
			elif y.run_end == None:
				return -1
			else:
				return cmp(x.run_end, y.run_end)

		for taskresult in sorted(result.taskresults, cmp=cmp_end_time):
			rfp.write("""
<h3>Task %s</h3>
<table>
  <tr>
    <td>Stage:</td>
    <td>%s</td>
  </tr>
  <tr>
    <td>Time:</td>
    <td>%s - %s (%s)</td>
  </tr>
  <tr>
    <td>Status:</td>
    <td style="background-color: %s;">%s</td>
  </tr>
""" % (cgi.escape(taskresult.name), taskresult.stage, \
	'?' if taskresult.run_start == None else taskresult.run_start, '?' if taskresult.run_end == None else taskresult.run_end, \
	'incomplete' if taskresult.run_end == None else taskresult.run_end - taskresult.run_start, \
	taskresult_to_color(taskresult), taskresult.status))

			if taskresult.run_end != None:
				rfp.write("""
  <tr>
    <th>Output:</th>
    <td><a href="../output/%d.html" target="_blank">open</a></td>
  </tr>
""" % (taskresult.id))
			rfp.write("""
</table>""")

			if len(taskresult.attributes) > 0:
				rfp.write("""
<table>
  <tr>
    <th>Parameter</th>
    <th style="text-align: left;">Value</th>
  </tr>
""")

				for (key, value) in taskresult.attributes.iteritems():
					rfp.write("""
  <tr>
    <td style="vertical-align: top;">%s</td>
    <td style="vertical-align: top;"><pre>%s</pre></td>
  </tr>
""" % (cgi.escape(str(key)), cgi.escape(str(value))))

				rfp.write("""
</table>
""")

			taskoutputfile = resultdir + '/output/' + str(taskresult.id) + '.html'
			if taskresult.run_end != None and not os.path.isfile(taskoutputfile):
				tfp = open(taskoutputfile, 'w')
				tfp.write("""
<html>
<head>
  <title>Task output for '%s'</title>
</head>
<body>
<h1>Task output for '%s'</h1>

<p>Job result: <a href="../results/%s.html">%s</a></p>

<pre>%s</pre>
</body>
</html>""" % (cgi.escape(taskresult.name), cgi.escape(taskresult.name), taskresult.jobresult.hash, taskresult.jobresult.hash, cgi.escape(taskresult.output)))
				tfp.close()

		rfp.close()

	jfp.write("""
</ul>

</body>
</html>
""")

	jfp.close()

mfp = open(resultdir + '/zfsci.html', 'w')

available_job_count = 0
for job in jobs:
	if job.available:
		available_job_count += 1

mfp.write("""
<html>
<head>
	<title>ZFSCI results</title>
</head>
<body>

<img src="zfsci.png" alt="ZFSCI results" />

<h2>Queue Status</h2>

There are %d jobs in the queue.

<h2>Legend</h2>

<table>
  <tr>
    <th style="background-color: red; width: 50px;" />
    <td>Build error</td>
  </tr>
  <tr>
    <th style="background-color: orange;" />
    <td>Build system problem</td>
  </tr>
  <tr>
    <th style="background-color: yellow;" />
    <td>Build in progress</td>
  </tr>
  <tr>
    <th style="background-color: green;" />
    <td>Successful build</td>
  </tr>
</table>

""" % (available_job_count))

timestamps = []

def find_branch_combinations(jobs):
	results = set()

	for job in jobs:
		if job.attributes['zfs-git-repo'] == None:
			continue

		result = (job.attributes['zfs-git-repo']['zfs-repository'], \
			job.attributes['zfs-git-repo']['spl-branch'], \
			job.attributes['zfs-git-repo']['zfs-branch'])

		results.add(result)

	return results

def get_timestamp(job):
	return int(job.attributes['zfs-git-repo']['timestamp'])

def get_host(job):
	return job.attributes['distribution'] + '<br />' + job.attributes['kernel-version']

def jobresult_to_color(result):
	if result.run_end == None:
		return 'yellow'

	type = result.get_result_type()

	if type == JobResult.SYSTEM_ERROR:
		return 'orange'
	elif type == JobResult.BUILD_ERROR:
		return 'red'
	else:
		return 'green'

def build_branch_table(fp, jobs, repository, splbranch, zfsbranch):
        html_id = md5(repository + splbranch + zfsbranch).hexdigest()

	fp.write("""
<table id="%s">
  <tr>
    <th>Repository</th>
    <td>%s</td>
  </tr>
  <tr>
    <th>SPL branch</th>
    <td>%s</td>
  </tr>
  <tr>
    <th>ZFS branch</th>
    <td>%s</td>
  </tr>
</table>
""" % (html_id, repository, splbranch, zfsbranch))

	def filter_job(job):
		if job.attributes['zfs-git-repo'] == None:
			return False

		if job.attributes['zfs-git-repo']['zfs-repository'] != repository:
			return False

		if job.attributes['zfs-git-repo']['spl-branch'] != splbranch or \
				job.attributes['zfs-git-repo']['zfs-branch'] != zfsbranch:
			return False

		return True

	jobs = filter(filter_job, jobs)

	hosts = []
	cells = {}

	for job in jobs:
		host = get_host(job)

		if host not in hosts:
			hosts.append(host)

		timestamp = get_timestamp(job)

		if not timestamp in cells:
			cells[timestamp] = []

		cells[timestamp].append(job)

	hosts = sorted(hosts)

	fp.write("""
<table>
<tr>
  <td>Timestamp / Host</td>
""")

	for host in hosts:
		fp.write('<td>' + host + '</td>')

	fp.write("""
</tr>
""")

	for timestamp in reversed(sorted(set(map(get_timestamp, jobs)))):
		fp.write("""
<tr>
  <td>%s</td>
""" % (datetime.fromtimestamp(timestamp)))

		for host in hosts:
			result = None

			for job in cells[timestamp]:
				if get_host(job) != host:
					continue

				best_result = None
				for result in job.results:
					if best_result == None or result.run_start > best_result.run_start:
						best_result = result
				result = best_result

				break

			if result == None:
				mfp.write('<td>&#8212;</td>') # Unicode EM DASH
				continue

			errors = result.count_errors()

			fp.write("""
<td style="background-color: %s;">
  <a href="results/%s.html">
    %d errors
  </a>
</td>""" % (jobresult_to_color(result), result.hash, errors))

		fp.write('</tr>')

	fp.write("""
</table>

</body>
</html>
""")

mfp.write("<h2>Test results</h2>")

for branch_combination in find_branch_combinations(jobs):
	build_branch_table(mfp, jobs, branch_combination[0], branch_combination[1], branch_combination[2])
	mfp.write("<br /><br />")

mfp.close()
