#!/usr/bin/env python2.6
import sys
import os
import glob
import json
from tasklib import Attribute, Utility

os.chdir(Utility.get_source_dir())

for taskfile in glob.glob('jobs/*.py'):
	cwd = os.getcwd()
	execfile(taskfile)
	os.chdir(cwd)

try:
	os.makedirs('build/jobs')
except OSError:
	pass

jobdescs = Attribute.get_jobdescs()
for jobdesc in jobdescs:
	fp = open('build/jobs/%s.json' % (jobdesc['job_id']), 'w')
	json.dump(jobdesc, fp)
	fp.close()

print 'Successfully built %d job descriptions.' % (len(jobdescs))

sys.exit(0)
