#!/usr/bin/env python
import sys
import os
import glob
from tasklib import Dispatcher

if len(sys.argv) < 3:
	print 'Syntax: %s <tasks-dir> <stage> [config-file]' % (sys.argv[0])
	sys.exit(1)

tasksdir = sys.argv[1]
stage = sys.argv[2]

if not os.path.isdir(tasksdir):
	print 'Tasks dir "%s" does not exist.' % (tasksdir)
	sys.exit(1)

if len(sys.argv) >= 4:
	configfile = sys.argv[3]

	if not os.path.isfile(configfile):
		print 'Config file "%s" does not exist.' % (configfile)
		sys.exit(1)

	Dispatcher.load_hive(configfile)

for taskfile in glob.glob('%s/*.py' % (tasksdir)):
	execfile(taskfile)

Dispatcher.run_stage(stage)

sys.exit(0)
