#!/bin/sh
[ -e /tmp/zfsci-picked-job ] && exit 0

echo "Picking job for node..."
mkdir -p /tmp/zfsci-job

for file in /var/lib/zfsci-data/jobs/*; do
	if [ ! -e $file ]; then
		continue
	fi

	if ! mv $file /tmp/zfsci-job/; then
		continue
	fi

	touch /tmp/zfsci-picked-job

	JOB=`basename $file`

	echo "Picked job: $JOB"

	if ! /opt/zfsci/zfsci-install-node /tmp/zfsci-job/$JOB; then
		exit 1
	fi

	if ! /opt/zfsci/zfsci-configure-node /tmp/zfsci-job/$JOB; then
		exit 1
	fi

	if ! /opt/zfsci/zfsci-boot-node; then
		exit 1
	fi

	exit 0
done

echo "No jobs found."
exit 1
