#!/bin/sh
exec 9>/tmp/zfsci-job-lock
if ! flock -x 9; then
	exit 1
fi

if [ -e /tmp/zfsci-picked-job ]; then
	exit 0
fi

if ! /opt/zfsci/zfsci-install-node DESTROY; then
	exit 1
fi

touch /tmp/zfsci-picked-job

if ! /opt/zfsci/zfsci-boot-node; then
	exit 1
fi

exit 0
